// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

type SupportedOAuthProvider = "google" | "apple" | "microsoft";

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: SupportedOAuthProvider,
      opts?: SignInOptions
    ) => {
      try {
        // 🔥 مهم: نضمن redirect صحيح دائمًا
        const redirectUri =
          opts?.redirect_uri ||
          `${window.location.origin}/auth/callback`;

        const result = await lovableAuth.signInWithOAuth(provider, {
          redirect_uri: redirectUri,
          extraParams: {
            ...opts?.extraParams,
          },
        });

        if (result?.error) {
          console.error("OAuth Error:", result.error);
          return { error: result.error };
        }

        // لو فيه redirect طبيعي من المزود
        if (result?.redirected) {
          return result;
        }

        // 🔥 حفظ session بشكل آمن
        if (result?.tokens) {
          await supabase.auth.setSession(result.tokens);
        }

        return result;
      } catch (e) {
        console.error("OAuth Exception:", e);
        return {
          error: e instanceof Error ? e : new Error(String(e)),
        };
      }
    },
  },
};
